### ISSUE TITLE
Webpack warning 'Critical dependencies: This seems to be a pre-built javascript file.'

### ISSUE THREAD

**Issue by JZiebikiewicz** [xErik/pdfmake-browserified#5]
Hi, I'm trying to use _pdfmake-browserified 0.1.4_ with webpack, but I get error:
```
[HMR] ./~/pdfmake-browserified/build/pdfmake-browserified.min.js
Critical dependencies:
1:482-489 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. 
Try to require the original source to get better results.
 @ ./~/pdfmake-browserified/build/pdfmake-browserified.min.js 1:482-489
```

Tried different import methods, like:
`const createPdf = require('pdfmake-browserified');`
`import createPdf from pdfmake-browserified';`
`import createPdf from '../../../node_modules/pdfmake-browserified/build/pdfmake-browserified.min.js';`

**Comment by xErik** [comment]
I am sorry, but I now nearly nothing about webpack :-(
